language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - PHPUNIT_FLAGS="-v"

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: SYMFONY_REQUIRE="3.4.*"
    - php: 7.2
      env: SYMFONY_REQUIRE="4.2.*"
    - php: 7.2
      env: SYMFONY_REQUIRE="4.3.*"
    - php: 7.2
      env: SYMFONY_REQUIRE="4.4.*"
    - php: 7.2
      env: SYMFONY_REQUIRE="5.0.*"
    - php: 7.3
    - php: 7.4
    - php: 7.4
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

  allow_failures:
    - env: COVERAGE=true

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - composer self-update
  - composer global require --no-scripts --no-plugins symfony/flex

install:
  - travis_retry composer update -n --prefer-stable --prefer-dist

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit $PHPUNIT_FLAGS
