language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COVERAGE=true PHPUNIT_FLAGS="--coverage-clover build/coverage.clover"
  allow_failures:
    - php: 7.0
    - php: hhvm
    - env: COVERAGE=true PHPUNIT_FLAGS="--coverage-clover build/coverage.clover"

install: travis_retry composer update

before_script:
  - if [ "$TRAVIS_PHP_VERSION" = "hhv*" ]; then cat .travis.ini >> /etc/hhvm/php.ini; fi;
  - if [ "$TRAVIS_PHP_VERSION" = "php*" ]; then phpenv config-add .travis.ini ; fi;

script:
  - vendor/bin/phpunit ${PHPUNIT_FLAGS}

after_script:
  - if [ $COVERAGE ]; then wget https://scrutinizer-ci.com/ocular.phar ; fi;
  - if [ $COVERAGE ]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.clover ; fi;
